dist: bionic
language: minimal

before_install:
    - sudo apt -y remove openjdk-11-jre openjdk-11-jdk
    - sudo apt -y install openjdk-8-jdk

install: true

script: JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/ mvn verify

