dist: bionic
language: minimal

before_install:
    - sudo apt -qq update > /dev/null
    - sudo apt -qq upgrade > /dev/null
    - sudo apt -qq remove openjdk-11-jre openjdk-11-jdk > /dev/null
    - sudo apt -qq install openjdk-8-jre openjdk-8-jdk maven > /dev/null

install: true

script: JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/ mvn verify -DconfigB=false -DconfigC=false

