dist: bionic
language: minimal

before_install:
    - sudo apt update
    - sudo apt remove openjdk-11-jre openjdk-11-jdk
    - sudo apt install openjdk-8-jre openjdk-8-jdk maven

install: true

script: JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/ mvn verify

